"""
Django settings for closedverse project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

PROD = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Generate one at: https://djecrety.ir/
SECRET_KEY = ''

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'le-kokomo.party'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ban',
	#pip3 install django-markdown-deux django-markdown2
	'markdown_deux',
    'closedverse_main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ban.middleware.BanManagement',
]

ROOT_URLCONF = 'closedverse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'closedverse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'oasis_db',
        'USER': 'oasis',
        'PASSWORD': 'password',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL = 'closedverse_main.User'
CSRF_FAILURE_VIEW = 'closedverse_main.views.csrf_fail'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/login/' 

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 's/')

STATIC_URL = '/s/'


# Media root
# This MUST end with a trailing slash and there must be an 'rm' folder in it
MEDIA_ROOT = os.path.join(BASE_DIR, 'i/')
# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://media.lawrence.com/media/", "http://example.com/media/"
MEDIA_URL = '/i/'

# Closedverse settings
# reCAPTCHA v2 keys, None for no reCAPTCHA
recaptcha_pub = '6LeYlX8aAAAAAEdFEwvoGfm0WrXQiZscIC7SWy5Y'
recaptcha_priv = '6LeYlX8aAAAAAKr8yKgyKatJ6oozHfxMTY8t03ac'

# NNID forbidden list. None for no passing.
nnid_forbiddens = BASE_DIR + '/forbidden.json'

# Memo title and message on communities list
memo_title = "Oasis"
memo_msg = " "
memo_title1 = "What is this? I thought it was dead?!"
memo_msg1 = "Oasis is now... A Oasis Clone I guess. You had enough of Closedverse Clones? Welcome Oasis clones."
memo_title2 = "Will Closedverse HACK ME?!?"
memo_msg2 =   "Pip and PF2M made Oasis, now SMF9 is rehosting it. This site is still based off Closedverse."
memo_title3 = "Will ME HACK Closedverse?!?"
memo_msg3 =    "No you should not worry about this since even I as the Owner can't see your IP when signing up I'm not evil and won't grab your IP or crap"
memo_title4 = "I want to be MOD."
memo_msg4   = "No it's boring at this point. AND ALSO DO NOT TRY TO ESCAPE A BAN. That is super annoying. For real."
memo_title5 = "pp"
memo_msg5 = "Thanks for asking but not for now. In fact yes, our Administration is supercharged etc."

# Client key to use for iphub.email, because we're using that
# None for no IP checking (recommended since this is so slow)
iphub_key = None

# If IP can be checked, then use this to disallow any proxies
disallow_proxy = True

# Cloudinary environment, because we're using that
# Never mind, not anymore
"""
cloudinary_key = None
cloudinary_secret = None
cloudinary_name = None
"""

# MD
MARKDOWN_DEUX_STYLES = {
    "default": {
        "extras": {
            "code-friendly": None,
        },
        "safe_mode": "escape",
    },
}

# Force logins everywhere.
force_login = True
# Don't change this.
LOGIN_EXEMPT_URLS = (
	r'^login/$',
	r'^signup/$',
	r'^logout/$',
	r'^reset/$',
	r'^help/rules$',
	r'^help/contact$',
	r'^help/login$',
)
# The location to redirect to if a user's status is set to 0 (Redirect)
active_redirect = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

# Option to delete image if it's local
# 0 - keep, 1 - move to 'rm' folder, 2 - DELETE
image_delete_opt = 2
