"""
Django settings for closedverse project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

PROD = False

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

ALLOWED_HOSTS = [
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	#pip3 install django-markdown-deux django-markdown2
	'markdown_deux',
    'closedverse_main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'closedverse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'closedverse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
		'OPTIONS': {'charset': 'utf8mb4'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = True

USE_L10N = True

USE_TZ = True

AUTH_USER_MODEL = 'closedverse_main.User'
CSRF_FAILURE_VIEW = 'closedverse_main.views.csrf_fail'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/login/' 

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]

STATIC_URL = '/s/'


# Media root
# This MUST end with a trailing slash and there must be an 'rm' folder in it
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash.
# Examples: "http://media.lawrence.com/media/", "http://example.com/media/"
MEDIA_URL = '/i/'

# Closedverse settings
# reCAPTCHA v2 keys, None for no reCAPTCHA
recaptcha_pub = None
recaptcha_priv = None

# NNID forbidden list. None for no passing.
nnid_forbiddens = BASE_DIR + '/forbidden.json'

# Memo title and message on communities list
memo_title = "What is Oasis? Or Oasisverse?! Which one is it?!?"
memo_msg = "It's like Closedverse, but with good-ish democratic ideas by Pip, hosting by PF2M, and done right this time. Also, it's Oasis"
memo_title = "Will Oasis Hack me?!?"
memo_msg = "No, Oasis will not hack you, that wouldn't be nice."
memo_title = "Will Me Hack Oasis?!?"
memo_msg = "You will NOT hack Oasis. That would also be mean."
memo_title = "Can I become Moderator, I'd love to help?!?!"
memo_msg = "Oasis is different. You have to be elected by your fellow users to get the power to enforce the rules. Also, please do not send me photos of your legs. That is bad. Do not."
memo_title = "Is this open source?!?"
memo_msg = "Yeah! https://github.com/Pikacraft64/oasis, but reminder, the code is a modification of Closedverse's"
memo_title = "Any ways to contact you?"
memo_msg = "Yeah! We have a contact page, and a discord sever! https://discord.gg/62Vnez2. Ask someone if the link doesn't work."

# Client key to use for iphub.email, because we're using that
# None for no IP checking (recommended since this is so slow)
iphub_key = None

# If IP can be checked, then use this to disallow any proxies
disallow_proxy = False

# Cloudinary environment, because we're using that
# Never mind, not anymore
"""
cloudinary_key = None
cloudinary_secret = None
cloudinary_name = None
"""

# MD
MARKDOWN_DEUX_STYLES = {
    "default": {
        "extras": {
            "code-friendly": None,
        },
        "safe_mode": "escape",
    },
}

# Force logins everywhere.
force_login = True
# Don't change this.
LOGIN_EXEMPT_URLS = (
	r'^login/$',
	r'^signup/$',
	r'^logout/$',
	r'^reset/$',
	r'^help/rules$',
	r'^help/contact$',
	r'^help/login$',
)
# The location to redirect to if a user's status is set to 2 (Redirect)
inactive_redirect = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

# Option to delete image if it's local
# 0 - keep, 1 - move to 'rm' folder, 2 - DELETE
image_delete_opt = 2
